### ISSUE TITLE
Leveraging SAMD51's TRNG

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/bc-lethekit#30]
There are parties that need to demonstrate that some of the randomness comes from a hardware based true random number generator (TRNG). For instance, some banking regulations and other standards require it (@kanzure do you know of some the specifics?).

As the AMD chip on the SAMD51 supports a TRNG, my suggestion is that when you are entering dice in the Seedtool, that if you press the `C` button it **safely** adds 1 TRNG call's worth of randomness to the dice already entered. The bits count would increment accordingly, and afterward you could continue to add additional dice of randomness.

Note that we probably need a unit test against if the randomness pool is too large and just submit for generation as soon as the randomness pool is full.

-- Christopher Allen

**Comment by ksedgwic** [comment]
This is all good except the
> The bits count would increment accordingly ...

With dice I know how much entropy is being added.  The only assumptions (fair dice, fair throws) are things the user can see, control and audit.

With the hardware PRNG I can't see, control or audit.  I'd be fine with displaying `Bits: 128.0 + ??` as a compromise.

I'm ok with someone else changing it to the way you like.  Not blindly trusting hardware PRNG is a personal issue, but one I'm unlikely to change my mind about ...

**Comment by ChristopherA** [comment]
> With the hardware PRNG I can't see, control or audit. I'd be fine with displaying Bits: 128.0 + ?? as a compromise.

Sounds good.

> I'm ok with someone else changing it to the way you like. Not blindly trusting hardware PRNG is a personal issue, but one I'm unlikely to change my mind about ...

I don't like to blindly trust them either. But there are some parties who only trust quantum hardware. Different rubric.

-- Christopher Allen
