### ISSUE TITLE
Battery retention posts too thin

### ISSUE THREAD

**Issue by howech** [BlockchainCommons/bc-lethekit#32]
On the case, the posts that hold the battery in place are too weak. I received an assembled kit in the mail, and three of the four posts had broken off in transit.

**Comment by ksedgwic** [comment]
I've seen one case of this as well; I dropped a unit from about 3ft up and it landed on the bottom edge.  The battery broke the bottom support off.

**Comment by Fonta1n3** [comment]
Same issue here, its working great though.

**Comment by ksedgwic** [comment]
Fixed in #33
