### ISSUE TITLE
Display blank (Waveshare 200x200, 1.54inch E-Ink display Rev2.1)

### ISSUE THREAD

**Issue by bavarianledger** [BlockchainCommons/bc-lethekit#34]
I've assembled the Lethekit, compiled and uploaded the SeedTool. But no luck getting it to work.

What is the expected "boot behavior" of the LetheKit? 
Has anyone created a short video showing the device powering up?

Mine is doing the following: blue LED turns on after powering it up, after ~1 second both LEDs are on for ~10 seconds, then the green LED turns off; nothing is shown on the display.

**Comment by ksedgwic** [comment]
The LED sequence indicates that the device is executing the initial self-test correctly.
1. If the bootstrap reaches the seedtool code we turn on both the blue and green LEDS.
2. During selftest the green LED is on until completion.  The 10 seconds sounds right to complete selftest.
3. During selftest the running tests are displayed on the display; it should not be blank.

So the strong indication is that the display (alone) is unhappy.  Please confirm the wiring between the display and the CPU.

You can confirm the system state and keypad (with the non-functioning display) currently by typing the following things (blind) after the initial bootup:
1. Power up, after the green light goes out press anything on the keypad once.
2. Press 'A' (Generate Seed)
3. Press '#' (Done, seed created w/ blank entropy)
At this point the green LED should come back on.  If it does problem is isolated to display.

**Comment by ChristopherA** [comment]
Are you certain that you've added code using the boot loader?

I personally have found it sometimes challenging to use the power-switch to get into bootloader mode. I found it it best to put two fingers on each side of the switch, start with the switch off and count fast 1-2-3 in about a second. Both blue & green lights will now be off despite the LetheKit being on.

-- Christopher Allen

**Comment by bavarianledger** [comment]
> Are you certain that you've added code using the boot loader?
> 
> I personally have found it sometimes challenging to use the power-switch to get into bootloader mode. I found it it best to put two fingers on each side of the switch, start with the switch off and count fast 1-2-3 in about a second. Both blue & green lights will now be off despite the LetheKit being on.
> 
> -- Christopher Allen

Yes, I think so.
I prefer entering the bootloader by pressing the reset button twice. 
And I've seen Arduino uploading and verifying the flash - about 98500 bytes.
So I guess this should be fine?

**Comment by ChristopherA** [comment]
>So I guess this should be fine?

Yes. Given that, my presumption is that the code is loaded, but like @ksedgwic said I suspect there is hardware display connection problem going on.

When I turn mine #LetheKit on, the blue LED light turns on and the paper display flashes full black twice. Then the green LED light also turns on and you see on the display "Running self tests:" at the top of the display, and the build number at the bottom, and then a scrolling list of self test starting with "seed generate", "bip39 generation", etc. to "TESTS PASSED". Then the green LED will go out leaving only the blue LED on. I've not stopwatch'ed it, but the green light for self-tests seems to be on about 10s.

Hope this last is useful. I'm not the hardware or Arduino expert on the team, learning just like you! 

-- Christopher Allen

**Comment by bavarianledger** [comment]
Thank you.
I noticed one difference while troubleshooting with @ksedgwic in my setup: the Waveshare E-Ink display says Rev2.1.

**Comment by ksedgwic** [comment]
Thanks to debugging support from @bavarianledger, we've found the problem.

Waveshare has started shipping a new version of the display ("Rev2.1 on the silkscreen).  Patching the hardware.{h,ino} files w/ s/GxEPD2_154/GxEPD2_154_D67/g fixes the problem.  Unfortunately the new driver doesn't work with the old displays so we're going to suffer some build/setup instruction pain (PR on the way).

Thanks again to @bavarianledger for finding and helping to fix this problem!

**Comment by ChristopherA** [comment]
I had started to put some software version numbers in my PR (https://github.com/BlockchainCommons/bc-lethekit/pull/29) — but I really don't have the background to finalize this PR as I don't have any previous Arduino experience. I'm glad to continue to test the Mac build, but the text changes in this PR really should be taken by someone else, ideally @ksedgwic but if not then @wolfmcnally.

**Comment by ksedgwic** [comment]
This issue is significantly addressed by #35 and #36 which are subsumed into #44
