### ISSUE TITLE
Display blank; doesn't seem to reset

### ISSUE THREAD

**Issue by ksedgwic** [BlockchainCommons/bc-lethekit#45]
This is a tracking bug to see if this problem is still present after #34

Originally reported and further researched by @gorazdko in #36 

Please add a comment to this issue if you see this problem.  Please include the software version number and display hardware version (legacy or v2.1) if possible,

**Comment by ksedgwic** [comment]
https://github.com/BlockchainCommons/bc-lethekit/pull/36#issuecomment-644212803

**Comment by gorazdko** [comment]
The bug happens occasionally.

The highlighted code looks problematic to me. The hardware reset does not happen on power on, but only after hibernation sleep. I checked the spec and reference code (https://github.com/waveshare/e-Paper/blob/853a3a4632fcb64a215e5335700f512b692bee91/Arduino/epd1in54_V2/epd1in54_V2.cpp#L83) and both suggest HW reset must be there.

I will test this once I come across the bug next time - it sometimes happen after lethekit has been on the shelf for a long time.

![image](https://user-images.githubusercontent.com/25270775/85589930-47fcc280-b644-11ea-9982-51874397e1a1.png)

**Comment by ksedgwic** [comment]
@gorazdko I have a display that is still blank.  I swapped it out because I couldn't recover it by power cycling, reconnecting etc.  It is always possible it is broken, however.

What is your recommended fix to try?  Should I remove the `if (_hibernating)` predicate and always `_reset()` in that routine?

**Comment by gorazdko** [comment]
> Should I remove the if (_hibernating) predicate and always _reset() in that routine?

That would be my guess, but i can't test because mine is working atm

The fastest way to see if the screen is working is by poking the vcc line during the selftest execution. Try also poking sck and mosi if vcc does not give results.

**Comment by ksedgwic** [comment]
I connected the previously blank display to a unit running the current master build (v0.4.6-g13c1cf9), was hoping to see it remain blank so i could see if your patch fixed it.

Of course it now works w/o trying the patch ;-)

I made a WIP PR with this change so we can try it easily when we see it next: #47

**Comment by gorazdko** [comment]
I think we can close this issue.

I haven't noticed any problems with the display and have been using it for quite a while now.

That one time i reported it, it must've been due to loose wiring.

**Comment by ksedgwic** [comment]
I also haven't seen the problem again.  Closing for now.
